# Permalinks
permalink: pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Retool app redesign
tagline:          'Retool UI Prototype'
url:              http://mattbond21.github.io/retool-design-prototype/
baseurl:          /retool-design-prototype/
