# Permalinks
permalink: pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Retool app redesign
tagline:          'Retool UI Prototype'
url:              http://tryretool.github.io/mb-design-prototype/
baseurl:          /mb-design-prototype/
